
db = CsvDatabase('F:\uni\nebenjob\data\NPI Neuroanatomy - Raw Data CFS-Files\Monkeys.csv', ...
    {'string'         ,'int32','datetime'        ,'int32','string','string'}, ...
    {'Monkey'         ,'Number','Date'           ,'Age','Sex'     ,'Species'}, ...
    {'char'           ,'int32','datetime'        ,'int32','char'  ,'char'},...
    {'Monkey'         ,'Number','Date'           ,'Age','Sex'     ,'Species'}, ...
    {''               ,''      ,datetime("today"),''     ,''      ,''},...
    {'Monkey'         ,'Number','Date'           ,'Age','Sex'     ,'Species'},...
    ';'...
    );

default = db.defaultStruct();

%data = db.inputDialog("test",{'','','',''});
data = db.request('Monkey','Eisenhez');
data.Sex = upper(data.Sex);

%db.save();